Cinema project using hibernate hw1
AndriiBardin/hibernateHW pull request #1
Opened 2021-01-26 12:36 UTC by AndriiBardin

2021-01-26 14:55 UTC, Max-Pochepets requested changes
check if all your files have an empty line in the end

2021-01-26 14:55 UTC, Max-Pochepets commented on src/main/java/cinema/dao/MovieDaoImpl.java
> +            movie.setId(itemId);
```suggestion
            session.save(movie);
            transaction.commit();
```
look [closely](https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html)

2021-01-26 14:55 UTC, Max-Pochepets commented on src/main/java/cinema/service/MovieService.java
> +
```suggestion
```

2021-01-26 14:55 UTC, Max-Pochepets commented on src/main/java/cinema/util/HibernateUtil.java
> +
```suggestion
```

2021-01-26 15:21 UTC, Max-Pochepets approved these changes

2021-01-27 08:05 UTC, Sofasmile requested changes

2021-01-27 08:05 UTC, Sofasmile commented on src/main/java/cinema/dao/MovieDao.java
> +    Movie add(Movie movie) throws DataBaseException;
```suggestion
    Movie add(Movie movie);
```

2021-01-27 08:05 UTC, Sofasmile commented on src/main/java/cinema/dao/MovieDaoImpl.java
> +    public Movie add(Movie movie) throws DataBaseException {
```suggestion
    public Movie add(Movie movie) {
```

2021-01-27 08:05 UTC, Sofasmile commented on src/main/java/cinema/dao/MovieDaoImpl.java
> +            throw new DataBaseException("Can't add movie entity");
```suggestion
            throw new DataBaseException("Can't add movie entity " + movie, e);
```

2021-01-27 08:05 UTC, Sofasmile commented on src/main/java/cinema/dao/MovieDaoImpl.java
> +            throw new DataBaseException("Can't get all movies");
```suggestion
            throw new DataBaseException("Can't get all movies", e);
```

2021-01-27 09:57 UTC, RomanDubovskyi requested changes

2021-01-27 09:57 UTC, RomanDubovskyi commented on src/main/java/cinema/dao/MovieDaoImpl.java
> +        } catch (DataBaseException e) {
```suggestion
        } catch (Exception e) {
```

2021-01-27 09:57 UTC, RomanDubovskyi commented on src/main/java/cinema/dao/MovieDaoImpl.java
> +        } catch (DataBaseException e) {
same

2021-01-27 11:15 UTC, RomanDubovskyi approved these changes

2021-02-01 14:30 UTC, merged