Update README.md
AndriiBardin/hibernateHW pull request #12
Opened 2021-02-27 07:27 UTC by AndriiBardin

2021-02-27 10:59 UTC, YuraBondarenko approved these changes

2021-03-01 08:04 UTC, KseniiaMakarova requested changes
let's merge PRs that need to be merged, and delete all redundant branches from GitHub

2021-03-01 08:04 UTC, KseniiaMakarova commented on README.md
> +The following layers were created **DB layer,** **DAO layer,** **Service layer,** **Controllers layer** and **View layer**
where is the view layer in your project?

2021-03-01 08:04 UTC, KseniiaMakarova commented on README.md
> +User allowed :
```suggestion
User is allowed to:
```

2021-03-01 08:04 UTC, KseniiaMakarova commented on README.md
> +### written by Andrii Bardin
what technologies did you use?

2021-03-01 08:04 UTC, KseniiaMakarova commented on README.md
> +- There are 2 user roles "USER" and "ADMIN". To log in as admin use "admin" as login "admin" as password
```suggestion
- There are 2 roles - "USER" and "ADMIN". To log in as admin use "admin" as login and "admin" as password
```

2021-03-01 08:43 UTC, KseniiaMakarova approved these changes

2021-03-01 08:43 UTC, KseniiaMakarova commented on README.md
> +- There are 2 user roles - "USER" and "ADMIN". To log in as admin use "admin" as and login "admin" as password
```suggestion
- There are 2 user roles - "USER" and "ADMIN". To log in as admin use "admin" as login and "admin" as password
```

2021-03-01 09:31 UTC, merged